language: cpp
os: linux
version: ~> 1.0

branches:
  only:
  - staging
  - trying
  - master
stages:
- name: sanitize
  if: type = cron
      AND repo = MirServer/mir
      AND branch = master

env:
  global:
    # SPREAD_GOOGLE_KEY
  - secure: C+R+J6LFdpge/aRDiCSVmU+Ps4sA0BhibQZgHi2iy20QkuD3NFiKcU7mISiEfWzsrRyLxtxYadWrfXXovyaSKDkIzuArVi/l5PyYRlLh7DYM/chk0CEbcoBpRKllgH57wU8ki7mCvksIbMdjZZo8iFIL79JUMaMvCK/QOwjqvj7d0I0qsJRT228G3n1KXKgRRL/9cafnjnzjHorrPpVJAkg8T7/QLO7uh7D5L5+KcHcf2Ws2/V05lhFXApCxL2QPLTCjn7cONKCaRfg35MkeFxWwTNm+JhGEW70A8Uk3qFWObWMPDEGrLkS5RF1Gw4zXrlqOyZRtK6VCaqsnJPVhqhLXliq9jNd/dbr/6L7hSa/t8ewbkXFuOqJzq240bEn4OCUFJOl9mwhklj14/Y+/xV3wRxIF6qdCDB99nirJKtwPjeYsKdCHLwKN/kj6yHhAU9JBDm+D5Odo9ny33eFPfQ+6SyGHL6BZKg7sVi8wbZwiTjmoN3wFZwSVto/4w1JiUHhJkMkEeIOlsQyfzJZl1DOTQDl4UiEAa8lhjvfqz8TqdXdu/3UPC9tokjnm45Joa5WkcnnvVsBoro+mSar6DipC6nb/+5yuguIEzcGha8iNyNMpMY0Ei0V+PwCl+M5k/vFtdA+HbSGs6VI4JvRd9awQ7geohn5ram5l4as67Sg=
  - DEBFULLNAME="Mir CI Bot"
  - DEBEMAIL="mir-ci-bot@canonical.com"
  - SPREAD_PATH=/tmp/spread

jobs:
  include:
  - &sanitize
    stage: sanitize
    env: TASK=google:ubuntu-20.04-64:spread/build/ubuntu:asan
  - <<: *sanitize
    env: TASK=google:ubuntu-20.04-64:spread/build/ubuntu:tsan
  - <<: *sanitize
    env: TASK=google:ubuntu-20.04-64:spread/build/ubuntu:ubsan
  - <<: *sanitize
    env: TASK=google:ubuntu-20.04-64:spread/build/ubuntu:asan_clang
  - <<: *sanitize
    env: TASK=google:ubuntu-20.04-64:spread/build/ubuntu:tsan_clang
  - <<: *sanitize
    env: TASK=google:ubuntu-20.04-64:spread/build/ubuntu:ubsan_clang

  fast_finish: true
