name: BuildTarball

on:
  workflow_dispatch:
    inputs:
      version:
        description: The version to build the tarball for
        required: true

jobs:
  BuildTarball:

    runs-on: ubuntu-latest

    steps:
    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v5
      with:
        gpg-private-key: ${{ secrets.MIR_BOT_GPG_PRIVATE_KEY }}

    - name: Check out code
      uses: actions/checkout@v3
      with:
        ref: v${{ inputs.ref }}

    - name: Build the tarball
      run: |
        ./tools/make_release_tarball --skip-checks
        gpg --detach-sig --sign --output mir-${{ inputs.version }}.tar.xz.asc mir-${{ inputs.version }}.tar.xz

    - name: Store the tarball and signature
      uses: actions/upload-artifact@v3
      path: |
        mir-${{ inputs.version }}.tar.xz
        mir-${{ inputs.version }}.tar.xz.asc
